### ISSUE TITLE
paleo initialization ice disappears on first time step

### ISSUE THREAD

**Issue by jalder-usgs** [CISM/cism#8] opened 2016-07-27 19:03 UTC
When initializing a 40 km North American domain with an LGM Laurentide Ice Sheet, the initialization ice disappears on the first time step (including Greenland ice) when using certain versions of GCC. This issue does not seem to appear when using modern initialization ice.

configuration where the error occurs:
Ubuntu 16.04
Linux version 4.4.0-22-generic
gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) 
NetCDF version : 4.4.3-1

Working configurations using the same sample file:
Ubuntu 14.04
Linux version 3.13.0-85-generic
gcc version 4.8.4
NetCDF Version: 1:4.1.3-7ubuntu2 (4.1.3-7 ???)

CentOS7
Linux version 3.10.0-229.14.1.el7.x86_64
gcc version 4.8.3 20140911 (Red Hat 4.8.3-9)
NetCDF (fortran) version: 4.4.2 

[vanishing_ice_sample.tar.gz](https://github.com/CISM/cism/files/386924/vanishing_ice_sample.tar.gz)

**Comment by jhkennedy** [comment] 2016-08-04 15:54
I've done a fresh install of Ubuntu 16.04 LTS, and before installing any of my packages, I just started working throught the CISM 2.0.5 user manual. 

So far, when installing packages via `apt-get`, `python-scientific` doesn't exist for 16.04 LTS, and `pip` is now `python-pip`. Otherwise the Ubuntu package installation commands are the same. 

I cannot build however because CISM cannot find `netcdf.mod`. 

I'm still working on that; I'll likely go through my preferred setup next and see how that works.

**Comment by jhkennedy** [comment] 2016-08-06 01:08
I've got CISM built now, so I'll try recreating the disappearing ice soon. 

To get `netcdf.mod` on Ubuntu 16.04 LTS, `libnetcdff-dev` needs to be installed in addition to `libnetcdf-dev`. Apparently, the Fortran netCDF library has been taken out of the normal netCDF development library for 16.04.

**Comment by jhkennedy** [comment] 2016-08-10 17:55
@jalder-usgs and @matthewhoffman, I'm unable to replicate this problem on Ubuntu 16.04 using CISM 2.0.5. 

Both ice6g and rsl120m seem to run just fine, and I don't see any disappearing ice. [vanishing_ice_test.tar.gz](https://github.com/CISM/cism/files/411749/vanishing_ice_test.tar.gz) contains the output log, stderr and stdout from the two runs (plus the config and input files needed to run). 

There are some slight differences between my machine and the configuration this didn't work on:

| Jalder's machine | My machine |
| --- | --- |
| Ubuntu 16.04 | Ubuntu 16.04 |
| Linux version 4.4.0-22-generic | Linux version 4.4.0-31-generic |
| gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) | gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) |
| NetCDF version : 4.4.3-1 | NetCDF version : 4.4.1 |

I've installed everything from the standard Ubuntu software repos. 

@jalder-usgs , if you still have access to the machine in that configuration, and have permission to update Ubuntu's packages, that might solve to problem.

**Comment by jalder-usgs** [comment] 2016-08-10 18:30
I was able to update my Ubuntu 16.04 machine to GCC 5.4, but it looks like the NetCDF package is unchanged. Once I updated and rebooted I did a make clean / cmake configure / make to rebuild CISM 2.0.5. However, I still get the same results of all the ICE6G ice volume being removed on the first step.

If this error is not reproducible or is specific to my machine configuration, do you think it is not worth pursuing? I have since gotten CISM 2.0.5 to build (GNU) on larger CentOS7 servers, so I no longer need this Ubuntu 16.04 machine for my research.

---
- Diagnostic output, time =      0.0000000000000000
- Total ice area (km^2)      0.2039840000000453E+08
- Total ice volume (km^3)    0.3572025951088376E+08
- Total ice energy (J)       0.0000000000000000E+00
- Mean thickness (m)          1751.1304568434691191
- Mean temperature (C)           0.0000000000000000
- Mean accum/ablat (m/yr)    0.0000000000000000E+00
- Mean basal melt (m/yr)     0.0000000000000000E+00
- Max thickness (m), i, j     4481.2436523437500000  73  68
- Max temperature, i, j, k       0.0000000000000000  68   7   1
- Min temperature, i, j, k       0.0000000000000000  68   7   1
- Max sfc spd (m/yr), i, j   40214.0454363109456608 148  52
- Max base spd (m/yr), i, j      0.0000000000000000  68   7
- ```
      Grid point diagnostics: (i,j) =   100    60
  ```
- ```
      Local (i,j,rank) =                100    60     0
  ```
- Upper surface (m)           2555.6478042602539062
- Thickness (m)               3165.3669433593750000
- Bedrock topo (m)            -609.7191390991210938
-    Relaxed bedrock (m)       126.1025768805453851
- Sfc mass balance (m/yr)        0.0000000000000000
- Basal melt rate (m/yr)         0.0000000000000000
- Basal water depth (m)          0.0000000000000000
- Basal heat flux (W/m^2)       -0.0500000000000000
-  Sigma       Ice speed (m/yr)       Ice temperature (C)
-  0.000     67.2073932803711358      0.0000000000000000
-  0.231     67.1104238783816243      0.0000000000000000
-  0.407     65.5588133164823290      0.0000000000000000
-  0.544     61.5649637409682100      0.0000000000000000
-  0.653     55.2544459076219354      0.0000000000000000
-  0.741     47.2257421093803558      0.0000000000000000
-  0.812     38.1320899022262765      0.0000000000000000
-  0.872     28.5192750663219101      0.0000000000000000
-  0.922     18.7914057948931159      0.0000000000000000
-  0.964      9.2256574138751510      0.0000000000000000
-  1.000      0.0000000000000000      0.0000000000000000
  
  ---
  
    Writing to file GENMOM_r1i1p24_namerica_40km.glint.nc at time    0.0000000000000000
  
  ---
  
    Writing to file GENMOM_r1i1p24_namerica_40km.hot.nc at time    0.0000000000000000
  
  ---
  
  ##   Writing to file GENMOM_r1i1p24_diag.glint.nc at time    0.0000000000000000
- Diagnostic output, time =      1.0000000000000000
- Total ice area (km^2)      0.0000000000000000E+00
- Total ice volume (km^3)    0.0000000000000000E+00
- Total ice energy (J)       0.0000000000000000E+00
- Mean thickness (m)             0.0000000000000000
- Mean temperature (C)           0.0000000000000000
- Mean accum/ablat (m/yr)    0.0000000000000000E+00
- Mean basal melt (m/yr)     0.0000000000000000E+00
- Max thickness (m), i, j        0.0000000000000000   1   1
- Max temperature, i, j, k    -999.0000000000000000   0   0   0
- Min temperature, i, j, k     999.0000000000000000   0   0   0
- Max sfc spd (m/yr), i, j -499500.0000000000000000   0   0
- Max base spd (m/yr), i, j-499500.0000000000000000   0   0
- ```
      Grid point diagnostics: (i,j) =   100    60
  ```
- ```
      Local (i,j,rank) =                100    60     0
  ```
- Upper surface (m)              0.0000000000000000
- Thickness (m)                  0.0000000000000000
- Bedrock topo (m)            -608.9836851713930628
-    Relaxed bedrock (m)       126.1025768805453851
- Sfc mass balance (m/yr)        0.1472575212391911
- Basal melt rate (m/yr)         0.0000000000000000
- Basal water depth (m)          0.0000000000000000
- Basal heat flux (W/m^2)       -0.0500000000000000
-  Sigma       Ice speed (m/yr)       Ice temperature (C)
-  0.000     67.2073932803711358      0.0000000000000000
-  0.231     67.1104238783816243      0.0000000000000000
-  0.407     65.5588133164823290      0.0000000000000000
-  0.544     61.5649637409682100      0.0000000000000000
-  0.653     55.2544459076219354      0.0000000000000000
-  0.741     47.2257421093803558      0.0000000000000000
-  0.812     38.1320899022262765      0.0000000000000000
-  0.872     28.5192750663219101      0.0000000000000000
-  0.922     18.7914057948931159      0.0000000000000000
-  0.964      9.2256574138751510      0.0000000000000000
-  1.000      0.0000000000000000      0.0000000000000000
  
  ---

**Comment by matthewhoffman** [comment] 2016-08-10 18:39
Thanks @jhkennedy for following up on this.  @jalder-usgs , I'd be inclined to think this is not worth pursuing since we are still unable to reproduce it.  It is a little disturbing that this sort of behavior could be out in the wild, but we'll have to deal with it as it is encountered.  I'm glad you were able to find an alternative machine to use.

I will close this issue for now then, but if it becomes a problem again in the future (for you or someone else in the community), it should be re-opened.

**Closed as completed by matthewhoffman** 2016-08-10 18:39 UTC

**Comment by jhkennedy** [comment] 2016-08-10 18:51
@jalder-usgs and @matthewhoffman , I agree, I'm not sure how to pursue it without reproducing it. 

One last thing to try though: @jalder-usgs can you `rm` all the cmake and build files (so you're only left with the linux cmake scripts). Then, can you try building the serial version again, but save the output for me from both the cmake scripts and the make command? If you're using bash, you can run these commands:

``` bash
source linux-gnu-serial-cmake > >(tee serial-cmake.out) 2> >(tee serial-cmake.err >&2)
make -j 1 > >(tee serial-build.out) 2> >(tee serial-build.err >&2)
```

They will make it so everything prints to your screen still (though without colorization) and make log files that contain the stdout and stderr streams.
